---
- name: Create users in bulk
  hosts: redhat.mlynx.pk
  become: yes
  vars:
    users:
      - name: faysalbank2
        password: "{{ 'bank2123' | password_hash('sha512', 'salt1') }}"
        uid: 1001
        gid: 10
        state: present
        shell: /bin/bash
        groups: wheel
        login_class: ""
        enabled: true
      - name: ibrahim-tester
        password: "{{ 'ibank123' | password_hash('sha512', 'salt1') }}"
        uid: 1002
        gid: 10
        state: present
        shell: /bin/bash
        groups: wheel
        login_class: ""
        enabled: true
  tasks:
    - name: Create or update user accounts
      user:
        name: "{{ item.name }}"
        password: "{{ item.password }}"
        uid: "{{ item.uid }}"
        group: "{{ item.gid }}"
        state: "{{ item.state }}"
        shell: "{{ item.shell }}"
        groups: "{{ item.groups }}"
        login_class: "{{ item.login_class }}"
        generate_ssh_key: "{{ item.enabled }}"
      with_items: "{{ users }}"
      become: yes
