- name: Manage Domain Controllers
  hosts: dns.mlynx.pk
  tasks:
    - name: Set DNS forwarders
      win_dns_client:
        dns_servers:
          - 8.8.8.8
          - 1.1.1.1
    - name: Create the user account
      win_user:
        name: ibrahim
        password: Mlynx@123
        state: present
        groups: "Domain Users"
        password_never_expires: yes
        description: "Testing Playbook by Ibrahim"    
