---
- name: Upgrade OS
  hosts: redhat.mlynx.pk
  become: true

  tasks:
    - name: Check if update is available
      command: "dnf check-update --refresh | grep -v '^.I'"
      register: update_available
      changed_when: false

    - name: Upgrade OS
      command: "dnf upgrade -y"
      when: update_available.stdout_lines != ''

    - name: Check if upgrade succeeded
      shell: "rpm -q rhel-8-for-x86_64 | awk '{print $3}'"
      register: os_version
      changed_when: false

    - name: Fail if upgrade failed
      fail:
        msg: "OS upgrade failed!"
      when: os_version.stdout_lines[0] != '8.7'

    - name: Reboot server
      reboot:
        msg: "OS upgrade requires a reboot"
      when: update_available.stdout_lines != ''
